-- general settings
require('plugins')
require('colorscheme')
require('settings')
require('keymaps')

-- plugin settings
require('nv-autopairs')
require('nv-buftabline')
require('nv-colorizer')
require('nv-comment')
require('nv-compe')
require('nv-dashboard')
require('nv-devicons')
require('nv-galaxyline')
require('nv-gitsigns')
require('nv-lspinstall')
require('nv-nvimtree')
require('nv-specs')
require('nv-telescope')
require('nv-terminal')
require('nv-treesitter')
require('nv-truezen')

-- lsp
require('lsp')
require('lsp.bash-ls')
require('lsp.cpp-ls')
require('lsp.css-ls')
require('lsp.golang-ls')
require('lsp.html-ls')
require('lsp.js-ts-ls')
-- require('lsp.json-ls')
-- require('lsp.latex-ls')
require('lsp.lua-ls')
require('lsp.php-ls')
require('lsp.python-ls')
-- require('lsp.ruby-ls')
require('lsp.rust-ls')
require('lsp.vim-ls')
-- require('lsp.yaml-ls')

-- vimscript only
vim.cmd('source ~/.config/nvim/vimscript/functions.vim')
