require("doom-one").setup({
	cursor_coloring = true,
	terminal_colors = true,
	italic_comments = true,
	enable_treesitter = true,
	transparent_background = false,
	pumblend = {
		enable = true,
		transparency_amount = 5,
	},
	plugins_integrations = {
		neorg = false,
		barbar = true,
		bufferline = false,
		gitgutter = false,
		gitsigns = true,
		telescope = true,
		neogit = false,
		nvim_tree = true,
		dashboard = false,
		startify = false,
		whichkey = false,
		indent_blankline = true,
		vim_illuminate = false,
		lspsaga = false,
	},
})
