vim.cmd('set colorcolumn=99999') -- fix indentline for now
vim.o.hidden = true
vim.o.title = true
vim.o.ruler = true
TERMINAL = vim.fn.expand('$TERMINAL')
vim.cmd('let &titleold="'..TERMINAL..'"')
vim.o.titlestring="%<%F%=%l/%L - nvim"
vim.wo.wrap = true
vim.cmd('set whichwrap+=<,>,[,],h,l')
vim.o.pumheight = 10
vim.o.fileencoding = "utf-8"
vim.o.cmdheight = 2
vim.o.mouse = "a"
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.conceallevel = 0
vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.smarttab = true
vim.bo.expandtab = true
vim.bo.smartindent = true
vim.o.autoindent = true
vim.o.laststatus = 2
vim.wo.number = true
vim.wo.cursorline = false
vim.o.showtabline = 2
vim.o.showmode = false
vim.o.backup = false
vim.o.writebackup = false
vim.wo.signcolumn = "yes"
vim.o.updatetime = 300
vim.o.timeoutlen = 500
vim.o.clipboard = "unnamedplus"
vim.o.paste = false
vim.o.scrolloff = 10
