return {
	"catppuccin/nvim",
	name = "catppuccin",
	term_colors = true,
	priority = 1000,
	opts = {
		styles = {
			comments = { "italic" },
			conditionals = { "italic" },
			loops = { "bold" },
			functions = { "italic" },
			keywords = { "italic" },
			strings = { "italic" },
			variables = { "bold" },
			numbers = { "bold" },
			booleans = { "italic" },
			properties = { "italic" },
			types = { "undercurl" },
			operators = { "bold" },
		},
		flavour = "frappe",
		integrations = {
			alpha = true,
			bufferline = true,
			cmp = true,
			gitsigns = true,
			harpoon = true,
			indent_blankline = {
				enabled = true,
				colored_indent_levels = false,
			},
			markdown = true,
			mason = true,
			mini = true,
			neotree = true,
			dap = {
				enabled = true,
				enable_ui = true, -- enable nvim-dap-ui
			},
			native_lsp = {
				enabled = true,
				virtual_text = {
					errors = { "italic" },
					hints = { "italic" },
					warnings = { "italic" },
					information = { "italic" },
				},
				underlines = {
					errors = { "underline" },
					hints = { "underline" },
					warnings = { "underline" },
					information = { "underline" },
				},
			},
			notify = true,
			telescope = true,
			lsp_trouble = true,
			treesitter = true,
			which_key = true,
		},
	},
}
